/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JshCurrencyField {
        /**
          * Represent the type of currency to use
         */
        "currency": string;
        /**
          * The amount value
         */
        "value": string;
    }
    interface JshWelcome {
        /**
          * The city where the conference is taking place (e.g. `Cluj-Napoca, Romania` )
         */
        "city": string;
        /**
          * The day the conference ends (e.g. `20th`)
         */
        "dayEnd": string;
        /**
          * The day the conference will start (e.g. `May 18`)
         */
        "dayStart": string;
        /**
          * The month in which the conference is taking place (e.g. `May`)
         */
        "month": string;
        /**
          * The year in which the conference is taking place (e.g. `2023`)
         */
        "year": string;
    }
}
export interface JshCurrencyFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJshCurrencyFieldElement;
}
declare global {
    interface HTMLJshCurrencyFieldElement extends Components.JshCurrencyField, HTMLStencilElement {
    }
    var HTMLJshCurrencyFieldElement: {
        prototype: HTMLJshCurrencyFieldElement;
        new (): HTMLJshCurrencyFieldElement;
    };
    interface HTMLJshWelcomeElement extends Components.JshWelcome, HTMLStencilElement {
    }
    var HTMLJshWelcomeElement: {
        prototype: HTMLJshWelcomeElement;
        new (): HTMLJshWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "jsh-currency-field": HTMLJshCurrencyFieldElement;
        "jsh-welcome": HTMLJshWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface JshCurrencyField {
        /**
          * Represent the type of currency to use
         */
        "currency"?: string;
        "onJshChange"?: (event: JshCurrencyFieldCustomEvent<any>) => void;
        /**
          * The amount value
         */
        "value"?: string;
    }
    interface JshWelcome {
        /**
          * The city where the conference is taking place (e.g. `Cluj-Napoca, Romania` )
         */
        "city"?: string;
        /**
          * The day the conference ends (e.g. `20th`)
         */
        "dayEnd"?: string;
        /**
          * The day the conference will start (e.g. `May 18`)
         */
        "dayStart"?: string;
        /**
          * The month in which the conference is taking place (e.g. `May`)
         */
        "month"?: string;
        /**
          * The year in which the conference is taking place (e.g. `2023`)
         */
        "year"?: string;
    }
    interface IntrinsicElements {
        "jsh-currency-field": JshCurrencyField;
        "jsh-welcome": JshWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jsh-currency-field": LocalJSX.JshCurrencyField & JSXBase.HTMLAttributes<HTMLJshCurrencyFieldElement>;
            "jsh-welcome": LocalJSX.JshWelcome & JSXBase.HTMLAttributes<HTMLJshWelcomeElement>;
        }
    }
}
